# Production environment override
services:
  php:
    build:
      context: ./api
      target: patreon_poll_prod
    environment:
      APP_SECRET: ${APP_SECRET}
      MERCURE_PUBLISHER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET}
      MERCURE_SUBSCRIBER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET}
      PATREON_ID: ${PATREON_ID}
      PATREON_SECRET: ${PATREON_SECRET}
    ports:
      # HTTP
      - target: 80
        published: 10000
        protocol: tcp
      # HTTPS
      - target: 443
        published: 10001
        protocol: tcp
      # HTTP/3
      - target: 443
        published: 10001
        protocol: udp
  database:
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
