hwi_oauth:
    # https://github.com/hwi/HWIOAuthBundle/blob/master/docs/2-configuring_resource_owners.md
    resource_owners:
        patreon:
            type:                oauth2
            class:               \HWI\Bundle\OAuthBundle\OAuth\ResourceOwner\OAuth2ResourceOwner
            client_id:           '%env(PATREON_ID)%'
            client_secret:       '%env(PATREON_SECRET)%'
            access_token_url:    'https://www.patreon.com/api/oauth2/token'
            authorization_url:   'https://www.patreon.com/oauth2/authorize'
            infos_url:           'https://www.patreon.com/api/oauth2/api/current_user'
            #scope:               "users pledges-to-me my-campaign"

